
import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'ru';

type Translations = {
    [key in Language]: {
        [key: string]: string;
    };
};

const translations: Translations = {
    en: {
        'nav.products': 'Products',
        'nav.solutions': 'Solutions',
        'nav.how_it_works': 'How it Works',
        'nav.integrations': 'Integrations',
        'nav.pricing': 'Pricing',
        'nav.resources': 'Resources',
        'nav.company': 'Company', // Optional if not present
        'nav.about': 'About',
        'nav.blog': 'Blog',
        'nav.careers': 'Careers',
        'nav.contact': 'Contact',
        'nav.login': 'Log In',
        'nav.book_demo': 'Book a Demo',
        'hero.title': 'Simulate your workforce',
        'hero.subtitle': 'Create AI employees that learn your business, qualify leads, and close deals while you sleep.',
        'hero.cta.start': 'Start for free',
        'hero.cta.book': 'Book a demo',
        'hero.promo': 'AI Employees · Built in minutes',
        'hero.headline_prefix': 'Your best employee',
        'hero.subheading': 'Hire an autonomous digital employee in a single conversation. No code. No training. Just results.',
        'hero.cta.create': 'Create your first employee — free',
        'hero.trusted': 'Trusted by',
        'hero.businesses': '2,400+ Businesses',
        'hero.search_placeholder': 'I need someone to handle client bookings...',
        'hero.phrases.0': 'never calls in sick.',
        'hero.phrases.1': 'works 24/7.',
        'hero.phrases.2': 'scales instantly.',
        'products.sales_manager': 'Sales Manager',
        'products.receptionist': 'Receptionist',
        'products.support_agent': 'Support Agent',
        'products.content_manager': 'Content Manager',
        'section.learn_more': 'Learn More',

        // Pain Section
        'pain.title': 'Sound',
        'pain.title_suffix': 'familiar?',
        'pain.subtitle': "Scaling a business is hard. Human limitations shouldn't be the bottleneck.",
        'pain.quote1': "A client messaged at 11pm asking to book.",
        'pain.quote1_highlight': "By morning they'd already gone to your competitor.",
        'pain.quote2': "Your manager is handling calls, WhatsApp, Instagram DMs and a spreadsheet — at the same time.",
        'pain.quote3': "You hired someone, trained them for 3 weeks,",
        'pain.quote3_highlight': "and they quit a month later.",
        'pain.quote4': "You're paying a full salary for someone who answers the same 10 questions every single day.",

        // How It Works
        'how.title': 'Onboard in',
        'how.title_suffix': 'minutes.',
        'how.subtitle': 'Hire an AI workforce that learns your business instantly.',
        'how.step1.title': '1. Define Role',
        'how.step1.desc': 'Tell us what you need. Sales Rep, Receptionist, or Support Agent.',
        'how.step2.title': '2. Sync Knowledge',
        'how.step2.desc': 'Upload your website, PDF, or Notion. The agent learns your business instantly.',
        'how.step3.title': '3. Delegate',
        'how.step3.desc': 'Your agent starts working 24/7 across WhatsApp, Web and Telegram.',

        // Capabilities
        'cap.title': 'Real work.',
        'cap.title_suffix': 'Not just chat.',
        'cap.card1.title': 'Instant Responses',
        'cap.card1.desc': 'Responds to every message in under 5 seconds. Never leaves a lead waiting.',
        'cap.card2.title': 'Bookings & Sales',
        'cap.card2.desc': 'Qualifies leads, books appointments, and takes payments automatically.',
        'cap.card3.title': 'Full Integration',
        'cap.card3.desc': 'Logs every conversation to your CRM and updates your calendar instantly.',

        // Catalog / Products
        'catalog.title': 'Ready to',
        'catalog.title_suffix': 'scale?',
        'catalog.subtitle': 'specialised AI agents designed to handle specific business functions with human-like precision.',

        'catalog.sales.title': 'AI Sales Manager',
        'catalog.sales.desc': 'Your top-performing sales rep, available 24/7. It engages leads instantly, qualifies them based on your playbook, answers complex objections, and closes deals or books meetings directly in the chat.',
        'catalog.sales.f1': 'Instant Lead Qualification',
        'catalog.sales.f2': 'Syncs with HubSpot/Salesforce',
        'catalog.sales.f3': 'Handles Objections Smartly',
        'catalog.sales.f4': 'Multi-channel: WhatsApp, Web, Telegram',

        'catalog.reception.title': 'AI Receptionist',
        'catalog.reception.desc': 'The front desk that never sleeps. Eliminate phone tag and missed opportunities. This agent handles scheduling, rescheduling, and sending reminders, ensuring your calendar is always full of qualified appointments.',
        'catalog.reception.f1': '24/7 Appointment Booking',
        'catalog.reception.f2': 'Google/Outlook/Calendly Sync',
        'catalog.reception.f3': 'Zero No-Shows (Smart Reminders)',
        'catalog.reception.f4': 'Intelligent Rescheduling',

        'catalog.support.title': 'AI Support Agent',
        'catalog.support.desc': 'Turn support into satisfaction. Resolve 80% of customer tickets instantly. It learns your entire knowledge base to track orders, handle returns, and troubleshoot issues, escalating only when necessary.',
        'catalog.support.f1': 'Instant FAQ Resolution',
        'catalog.support.f2': 'Real-time Order Tracking',
        'catalog.support.f3': 'Seamless Human Hand-off',
        'catalog.support.f4': '95+ Languages Supported',

        'catalog.content.title': 'AI Content Manager',
        'catalog.content.desc': 'Your always-on social media team. Keep your brand active without the burnout. It writes engaging posts, auto-schedules content, and replies to comments to boost community engagement.',
        'catalog.content.f1': 'Drafts & Schedules Posts',
        'catalog.content.f2': 'Auto-Replies to Comments',
        'catalog.content.f3': 'Viral Trend Analysis',
        'catalog.content.f4': 'Adapts to Your Brand Voice',

        // Integrations
        'integ.title': '100+ Seamless Integrations',
        'integ.desc': 'Connect your favorite tools with a single click.',
        'integ.nocode': 'No coding required.',
        'integ.desc2': 'Our AI engine instantly learns your stack and starts working across all platforms seamlessly.',
        'integ.soc2': 'SOC2 Compliant',
        'integ.visual.init': 'INITIALIZING_SYNC_PROTOCOL...',
        'integ.visual.target': 'Target: 100+ Integrations',

        // Comparison
        'comp.title': 'The numbers',
        'comp.title_suffix': "don't lie.",
        'comp.metric': 'Metric',
        'comp.human': 'Human',
        'comp.ai': 'X100 AI',
        'comp.m1': 'Response time', 'comp.h1': '2–8 hours', 'comp.a1': '3 seconds',
        'comp.m2': 'Availability', 'comp.h2': '5 days, 9-5', 'comp.a2': '24/7/365',
        'comp.m3': 'Monthly cost', 'comp.h3': '60 000 ₽+', 'comp.a3': 'from 14 900 ₽',
        'comp.m4': 'Training time', 'comp.h4': '3–4 weeks', 'comp.a4': '7 minutes',
        'comp.m5': 'Concurrent chats', 'comp.h5': '1–2', 'comp.a5': 'Unlimited',
        'comp.disclaimer': "*X100 doesn't replace people. It handles repetitive work so your team can focus on what actually matters.",





        // Footer
        'footer.roi': 'Immediate ROI',
        'footer.title': 'Scale your team',
        'footer.title_suffix': 'without',
        'footer.title_suffix2': 'the overhead.',
        'footer.subtitle': 'Deploy an AI Sales Manager or Support Agent today. Zero training time. Infinite scalability.',
        'footer.cta': 'Start Hiring AI',
        'footer.stat.uptime': 'Uptime',
        'footer.stat.automated': 'Automated',
        'footer.card.growth_engine': 'Growth Engine',
        'footer.card.running': 'Running at 100%',
        'footer.card.leads': 'Leads Processed',
        'footer.card.revenue': 'Revenue Generated',
        'footer.card.team_perf': 'Team Performance: All Systems Go',
        'footer.col.roles': 'Roles',
        'footer.col.company': 'Company',
        'footer.col.legal': 'Legal',
        'footer.disclaimer': 'Made for businesses that refuse to miss a single client.',
        'footer.legal.copyright': '©2026 X100 Inc. All rights reserved.',
        'footer.legal.text': 'X100 creates autonomous digital agents. Results may vary based on configuration and training data.',
        'footer.email_placeholder': 'Enter your email',
        'footer.join': 'Join',
        'products.personal_assistant': 'Personal Assistant',

        // About Page
        'about.mission.title': 'Our',
        'about.mission.title_suffix': 'Mission.',
        'about.mission.subtitle': 'We are building the autonomous workforce of the future. Our goal is to liberate humans from mundane tasks, enabling them to focus on creativity, strategy, and innovation.',
        'about.problem.title': 'The',
        'about.problem.title_suffix': 'Problem',
        'about.problem.p1': 'For decades, businesses have scaled by adding headcount. This linear model is broken. It\'s slow, expensive, and stressful. Humans burn out. They make mistakes. They need sleep.',
        'about.problem.p2': 'We believe that 80% of modern knowledge work is repetitive and can be automated. Yet, most automation tools are too rigid or too complex to set up.',
        'about.problem.visual': 'Visual: Human vs Machine Graph',
        'about.solution.title': 'The Solution:',
        'about.solution.title_suffix': 'X100',
        'about.solution.p1': 'X100 is not just a chatbot. It\'s a comprehensive specific agent architecture. We build digital employees that can learn, adapt, and execute complex workflows without supervision.',
        'about.solution.p2': 'Our agents don\'t just "talk"—they "do". They access your CRM, manage your calendar, and process payments. They are true autonomous entities.',
        'about.solution.visual': 'Visual: Agent Neural Network',
        'about.leadership.title': 'Leadership',
        'about.team.david.name': 'David Chen',
        'about.team.david.role': 'CEO & Founder',
        'about.team.sarah.name': 'Sarah Miller',
        'about.team.sarah.role': 'CTO',
        'about.team.james.name': 'James Wilson',
        'about.team.james.role': 'Head of AI',

        // Blog Page
        'blog.title': 'The',
        'blog.title_suffix': 'Signal.',
        'blog.subtitle': 'Insights on AI, automation, and the future of work.',
        'blog.read_article': 'Read Article',
        'blog.back_to_blog': 'Back to Blog',
        'blog.read_next': 'Read Next',

        'blog.post1.title': 'The Death of the Call Center: Why AI Agents Are Inevitable',
        'blog.post1.date': 'Feb 12, 2026',
        'blog.post1.author': 'Alex V.',
        'blog.post1.summary': 'Traditional call centers are expensive, inefficient, and prone to human error. AI agents handle 24/7 support with zero wait times.',

        'blog.post2.title': 'How to Train Your AI Sales Manager in 7 Minutes',
        'blog.post2.date': 'Feb 08, 2026',
        'blog.post2.author': 'Sarah J.',
        'blog.post2.summary': 'You don\'t need a developer. Upload your PDFs, sync your website, and watch your AI agent start qualifying leads automatically.',

        'blog.post3.title': 'The Economics of AI: Calculating ROI for Small Business',
        'blog.post3.date': 'Jan 28, 2026',
        'blog.post3.author': 'David R.',
        'blog.post3.summary': 'Compare the cost of a full-time employee vs. an AI agent. The math is simple: 10x output for 1/100th of the price.',

        'blog.post4.title': 'Voice AI vs. Text AI: Which One Does Your Business Need?',
        'blog.post4.date': 'Jan 15, 2026',
        'blog.post4.author': 'Michael T.',
        'blog.post4.summary': 'Voice agents handle phone calls with human-like nuance. Text agents dominate chat apps. Here\'s how to choose the right mix.',

        'blog.post5.title': 'Future of Work: Managing a Hybrid Human-AI Team',
        'blog.post5.date': 'Jan 03, 2026',
        'blog.post5.author': 'Emma W.',
        'blog.post5.summary': 'AI isn\'t replacing humans; it\'s augmenting them. Learn how to structure your team where AI handles the grunt work and humans handle strategy.',

        // Contact Page
        'contact.title': 'Get in',
        'contact.title_suffix': 'touch.',
        'contact.subtitle': 'Whether you have a question about features, pricing, or enterprise solutions, our team is ready to answer.',
        'contact.headquarters': 'Headquarters',
        'contact.headquarters.address': '100 Market Street, Suite 500',
        'contact.headquarters.city': 'San Francisco, CA 94103',
        'contact.email': 'Email Us',
        'contact.email.hello': 'hello@x100.ai',
        'contact.email.support': 'support@x100.ai',
        'contact.follow': 'Follow Us',
        'contact.social.twitter': 'Twitter/X',
        'contact.social.linkedin': 'LinkedIn',
        'contact.social.instagram': 'Instagram',
        'contact.form.name': 'Name',
        'contact.form.email': 'Email',
        'contact.form.message': 'Message',
        'contact.form.name.placeholder': 'John Doe',
        'contact.form.email.placeholder': 'john@company.com',
        'contact.form.message.placeholder': 'How can we help you?',
        'contact.form.submit': 'Send Message',
        'contact.form.sending': 'Sending...',
        'contact.success.title': 'Message Sent',
        'contact.success.subtitle': 'We\'ll get back to you within 24 hours.',
        'contact.success.send_another': 'Send another message',

        // Careers Page
        'careers.title': 'Join the',
        'careers.title_suffix': 'revolution.',
        'careers.subtitle': 'We are a team of builders, dreamers, and optimists. We\'re hiring the smartest people in the world to solve the hardest problems in AI.',
        'careers.autonomy.title': 'Autonomy',
        'careers.autonomy.desc': 'We don\'t micromanage. We hire adults and give them the freedom to execute. You own your projects from start to finish.',
        'careers.impact.title': 'Impact',
        'careers.impact.desc': 'Your work will directly affect thousands of businesses. We are changing the very fabric of how the economy operates.',
        'careers.positions.title': 'Open',
        'careers.positions.title_suffix': 'Positions',
        'careers.job1.title': 'Senior AI Engineer',
        'careers.job1.department': 'Engineering',
        'careers.job1.location': 'Remote (Global)',
        'careers.job1.type': 'Full-time',
        'careers.job2.title': 'Product Designer',
        'careers.job2.department': 'Design',
        'careers.job2.location': 'Remote (US/EU)',
        'careers.job2.type': 'Full-time',
        'careers.job3.title': 'Enterprise Sales Lead',
        'careers.job3.department': 'Sales',
        'careers.job3.location': 'New York, NY',
        'careers.job3.type': 'Full-time',
        'careers.job4.title': 'Growth Marketing Manager',
        'careers.job4.department': 'Marketing',
        'careers.job4.location': 'Remote',
        'careers.job4.type': 'Full-time',
        'careers.no_fit': 'Don\'t see a role that fits?',
        'careers.general_application': 'Email General Application',
        // Login
        'login.title': 'Get Started',
        'login.title_suffix': 'with Us',
        'login.subtitle': 'Complete these easy steps to access your AI workforce and start automating today.',
        'login.step1': 'Log in to account',
        'login.step2': 'Connect your agents',
        'login.step3': 'Start automating',
        'login.form.title': 'Login Account',
        'login.form.subtitle': 'Enter your personal data to access your workspace.',
        'login.email': 'Email',
        'login.password': 'Password',
        'login.forgot': 'Forgot Password?',
        'login.min_chars': 'Must be at least 8 characters.',
        'login.submit': 'Log In',
        'login.footer': "Don't have an account?",
        'login.footer_link': 'Sign up',
        // Register
        'register.title': 'Create your',
        'register.title_suffix': 'digital workforce',
        'register.subtitle': 'Start building AI employees in minutes',
        'register.form.title': 'Create your account',
        'register.form.subtitle': 'Join thousands of businesses automating with AI',
        'register.company': 'Company Name',
        'register.submit': 'Create Account',
        'register.footer': 'Already have an account?',
        'register.footer_link': 'Log in',
        // Features
        'features.title': 'Financial wellness,',
        'features.title_suffix': 'reinvented.',
        'features.subtitle': 'Everything you need to manage your wealth, from equity management to tax filing, all in one place.',
        'features.net_worth.title': 'Total Net Worth',
        'features.net_worth.desc': 'Connect all your accounts for a holistic view of your finances. Real-time tracking of assets, liabilities, and equity.',
        'features.tax.title': 'Tax Filing',
        'features.tax.desc': 'Automated tax filing designed for modern compensation packages.',
        'features.equity.title': 'Equity Management',
        'features.equity.desc': 'Track vesting schedules, exercise options, and model future scenarios.',
        'features.retirement.title': 'Retirement',
        'features.retirement.desc': 'Personalized roadmaps to help you hit your freedom number faster.',
        'features.advisory.title': 'Expert Advisory',
        'features.advisory.desc': 'Unlimited access to CFP® professionals for complex questions.',
        'features.more_about': 'More about',
        // Impact Features
        'impact.title': 'Built for',
        'impact.title_suffix': 'Growth.',
        'impact.subtitle': "X100 isn't just software. It's a scalable infrastructure that replaces overhead with profit margins.",
        'impact.card1.title': 'Maximize Revenue',
        'impact.card1.desc': 'X100 agents never sleep. Every lead is engaged instantly, qualified automatically, and booked directly into your calendar.',
        'impact.card1.stat_label': 'Lead Capture',
        'impact.card2.title': 'Instant Scale',
        'impact.card2.desc': 'Handle 1 or 10,000 concurrent conversations without adding headcount.',
        'impact.card3.title': 'Enterprise Security',
        'impact.card3.desc': 'Data encryption, role-based access, and GDPR compliance built-in.',
        'impact.card4.title': 'Zero Human Error',
        'impact.card4.desc': 'Forget about sick days, missed details, or training gaps. X100 agents follow your playbook perfectly, every single time.',
        // Product Demo
        'demo.title': 'Complete',
        'demo.title_suffix': 'control.',
        'demo.subtitle': 'From creation to analysis, manage your entire digital workforce from a single command center.',
        'demo.tab1': 'Build',
        'demo.tab2': 'Manage',
        'demo.tab3': 'Scale',
        'demo.tab1.title': 'The Architect',
        'demo.tab1.desc': 'Describe your ideal employee in plain English. The Architect builds the agent, configures the tools, and syncs your knowledge base instantly.',
        'demo.tab2.title': 'Active Workforce',
        'demo.tab2.desc': 'View your team of digital agents in one dashboard. Monitor their status, pause them anytime, or deploy new ones with a single click.',
        'demo.tab3.title': 'Intelligence',
        'demo.tab3.desc': 'Track real-time performance. See exactly how much revenue your agents generate and how many hours of manual work they save.',
        // Product Demo Mocks
        'demo.mock.chat.ai_greeting': 'I am X100 Architect. What kind of employee do you need to hire today?',
        'demo.mock.chat.user_req': 'I need a Sales Manager to handle inbound leads from our website and book demos on my calendar.',
        'demo.mock.chat.ai_response': "Understood. I'm configuring a",
        'demo.mock.chat.role_name': 'Sales Manager',
        'demo.mock.chat.with_capabilities': 'with the following capabilities:',
        'demo.mock.chat.cap1': 'Lead Qualification',
        'demo.mock.chat.cap2': 'Calendar Sync',
        'demo.mock.chat.cap3': 'CRM Update',
        'demo.mock.chat.upload_prompt': 'Would you like to upload your pricing PDF for training?',

        'demo.mock.workforce.title': 'My Workforce',
        'demo.mock.workforce.subtitle': '24/7 Operations',
        'demo.mock.workforce.system': 'Systems Nominal',
        'demo.mock.workforce.agent1.role': 'Sales Agent',
        'demo.mock.workforce.agent1.metric1': 'Response Time',
        'demo.mock.workforce.agent1.metric2': 'Deals Closed',
        'demo.mock.workforce.agent1.footer': 'Saved 42hrs this week',
        'demo.mock.workforce.agent2.role': 'Receptionist',
        'demo.mock.workforce.agent2.metric1': 'Calls Handled',
        'demo.mock.workforce.agent2.metric2': 'Bookings',
        'demo.mock.workforce.agent2.footer': '0 missed calls',
        'demo.mock.workforce.hire': 'Hire New Agent',

        'demo.mock.analytics.title': 'Performance',
        'demo.mock.analytics.period': 'Last 7 Days',
        'demo.mock.analytics.roi': 'ROI Generated',
        'demo.mock.analytics.man_hours': 'Man-Hours',
        'demo.mock.analytics.saved': 'saved',
        'demo.mock.analytics.cost_lead': 'Cost/Lead',
        'demo.mock.analytics.avg': 'avg',

        // Testimonial Marquee
        'testim.trusted': 'Trusted by 2,400+ Businesses',
        'testim.switch': 'switch.',
        'testim.subtitle': 'See how companies are replacing manual work with autonomous AI agents.',
        'testim.q1': "We set up our receptionist in 9 minutes. The next morning she had already booked 23 appointments while we were asleep.",
        'testim.q2': "Our sales manager used to lose leads after hours. Now X100 catches every single one. Revenue up 40% in the first month.",
        'testim.q3': "I was skeptical — I'm not technical at all. But my assistant was running in under 10 minutes. It's like hiring someone who already knows the job.",
        'testim.q4': "Our response time dropped from 4 hours to 30 seconds. Customer satisfaction scores hit an all-time high within a week.",
        'testim.q5': "Screened 500 resumes in an afternoon. We hired our top engineer within 3 days. The AI Recruiter finds hidden gems humans miss.",
        'testim.q6': "The agent qualifies leads 24/7. I wake up to a calendar full of serious buyers ready to close. It changed my real estate business.",
        'testim.q7': "Handles returns and tracking questions instantly. My support team can finally focus on complex issues instead of repetitive tickets.",
        'testim.q8': "We scaled to 50 clients without hiring a single new account manager. X100 handles the daily communications perfectly.",
        'testim.q9': "It engages with every DM on Instagram. My course sales have doubled since installing the Content Manager. Absolute game changer.",

        // Testimonial Authors & Roles
        'testim.n1': "Maria K.", 'testim.r1': "Bloom Beauty Studio",
        'testim.n2': "Artem V.", 'testim.r2': "Forma Furniture",
        'testim.n3': "Olga S.", 'testim.r3': "LegalEase Consulting",
        'testim.n4': "Liam T.", 'testim.r4': "TechFlow Support",
        'testim.n5': "Sarah J.", 'testim.r5': "HR Director",
        'testim.n6': "David R.", 'testim.r6': "Prime Realty",
        'testim.n7': "James L.", 'testim.r7': "E-commerce Founder",
        'testim.n8': "Elena M.", 'testim.r8': "Digital Agency CEO",
        'testim.n9': "Marcus B.", 'testim.r9': "Performance Coach",

        // Visual Mocks in ProductSections
        'visual.sales.user': 'How much for the enterprise plan?',
        'visual.sales.agent': "It's 39 900 ₽/mo. It includes unlimited agents and a dedicated account manager. Would you like to book a demo?",
        'visual.sales.tag': 'Lead Qualified: Hot 🔥',

        'visual.reception.calendar': 'Calendar',
        'visual.reception.syncing': 'Syncing...',
        'visual.reception.booking': 'Booking: Sarah J.',
        'visual.reception.time': 'Tomorrow, 10:00 AM',
        'visual.reception.confirmed': 'Confirmed',
        'visual.reception.haircut': 'Haircut & Style',
        'visual.reception.reminder': 'Auto-reminder sent',

        'visual.support.user': 'Where is my order #1234?',
        'visual.support.agent': 'Order #1234 is out for delivery! It should arrive by 2 PM today. Here is the tracking link.',
        'visual.support.kb': 'Knowledge Base',
        'visual.support.response': 'Response: 1.2s',

        'visual.content.drafting': 'Drafting: Instagram Post',
        'visual.content.post': '"Boost your productivity with our new AI tools! 🚀 #Tech #AI"',

        // Capabilities Visuals
        'visual.cap.user': 'Do you have availability tomorrow?',
        'visual.cap.agent_check': 'Checking calendar...',
        'visual.cap.agent_confirm': 'Yes, I have a slot at 2:00 PM. Should I book it?',

        'visual.booking.new': 'New Event',
        'visual.booking.demo': 'Demo Call',
        'visual.booking.time_label': 'Time',
        'visual.booking.time_val': 'Tomorrow, 10:00 AM',
        'visual.booking.guest_label': 'Guest',
        'visual.booking.confirmed': 'Confirmed',

        'visual.integration.hubspot': 'Contact created',
        'visual.integration.just_now': 'Just now',
        'visual.integration.salesforce': 'Deal stage updated',
        'visual.integration.ago_2m': '2m ago',
        'visual.integration.slack': 'Notification sent',
        'visual.integration.ago_5m': '5m ago',
        'visual.integration.gmail': 'Follow-up scheduled',
        'visual.integration.ago_12m': '12m ago',
        'footer.nav.privacy': 'Privacy Policy',
        'footer.nav.terms': 'Terms of Service',
        'footer.nav.gdpr': 'GDPR',

        // Cookie Consent
        'cookie.title': '🍪 Cookie Preferences',
        'cookie.text': 'We use cookies to enable our AI features and analyze traffic. No personal data is sold to third parties.',
        'cookie.accept': 'Accept All',
        'cookie.decline': 'Necessary Only',

        // Insight Recap
        'recap.cta.title': 'See X100 in Action',
        'recap.cta.desc': 'Watch how to build a fully functional support team in under 10 minutes.',
        'recap.cta.btn': 'Watch Demo',

        'recap.left.title_em': 'Monitor',
        'recap.left.title': 'team output',
        'recap.left.subtitle': 'Real-time dashboard of your digital workforce productivity and customer engagement.',
        'recap.left.card_title': 'Support Bot handled 1,500 tickets',
        'recap.left.card_desc': 'Your Tier-1 support agent successfully resolved 98% of incoming queries in the last 24 hours. Customer satisfaction score rose to 4.9/5.',

        'recap.right.title_em': 'Daily',
        'recap.right.title': 'business recaps',
        'recap.right.subtitle': 'Your business performance, summarized daily—stay in sync with leads, conversions, and operations.',
        'recap.right.card_title': '342 New Leads Generated',
        'recap.right.card_desc': 'The SEO Manager agent successfully ranked 3 new blog posts, resulting in a 20% spike in traffic.',
        'recap.right.recents': 'Recent Conversions',
        'recap.right.report': 'Detailed Report',

        'recap.tx.ent': 'Enterprise Plan', 'recap.tx.ent_sub': 'Sales Agent · 10 min ago',
        'recap.tx.start': 'Starter Plan', 'recap.tx.start_sub': 'Web Bot · 1 hour ago',
        'recap.tx.consult': 'Consultation', 'recap.tx.consult_sub': 'Booking Bot · 2 hours ago',

        // Gemini Advisor
        'advisor.title': 'Simulate your', 'advisor.title_suffix': 'workforce.',
        'advisor.subtitle': 'See exactly how an AI employee fits into your business. No code, no complexity.',
        'advisor.status': 'Active Now',
        'advisor.active': 'Active Now',
        'advisor.cost': 'Cost',
        'advisor.human': 'Human Equivalent',
        'advisor.price.89': '24 900 ₽/мес',
        'advisor.price.5000': '500 000 ₽/мес',
        'advisor.price.3500': '350 000 ₽/мес',
        'advisor.price.3000': '300 000 ₽/мес',
        'advisor.price.4500': '450 000 ₽/мес',

        // Agents
        'advisor.agent.sales.name': 'Sales Manager', 'advisor.agent.sales.role': 'Revenue Growth',
        'advisor.agent.sales.desc': "I work your leads 24/7. While you sleep, I'm chatting with prospects on WhatsApp, handling objections, and closing deals.",
        'advisor.agent.sales.benefit': "Wakes you up to 'Payment Received' notifications.",

        'advisor.agent.support.name': 'Support Agent', 'advisor.agent.support.role': 'Customer Success',
        'advisor.agent.support.desc': "I memorize your entire help desk. I resolve refunds, track orders, and answer technical questions instantly.",
        'advisor.agent.support.benefit': "Achieves 'Inbox Zero' every single day.",

        'advisor.agent.receptionist.name': 'Receptionist', 'advisor.agent.receptionist.role': 'Front Desk',
        'advisor.agent.receptionist.desc': "I manage your calendar like a pro. I book slots, send reminders, and reschedule meetings without you lifting a finger.",
        'advisor.agent.receptionist.benefit': "Fills your calendar with qualified meetings.",

        'advisor.agent.recruiter.name': 'HR Recruiter', 'advisor.agent.recruiter.role': 'Talent Acquisition',
        'advisor.agent.recruiter.desc': "I read thousands of resumes in minutes. I find the top 1% of talent and schedule interviews for you.",
        'advisor.agent.recruiter.benefit': "Delivers the perfect candidate on a silver platter.",

        // Visuals
        'advisor.visual.sales.p1.title': 'New Stripe Payment: 120 000 ₽', 'advisor.visual.sales.p1.sub': 'Closed from WhatsApp Lead',
        'advisor.visual.sales.p2.title': 'Lead Qualified: TechCorp', 'advisor.visual.sales.p2.sub': 'Budget: Enterprise • Ready to buy',
        'advisor.visual.sales.p3.title': 'Demo Booked: Tuesday 2pm', 'advisor.visual.sales.p3.sub': 'Auto-scheduled via Calendar',
        'advisor.visual.sales.today': "Today's Pipeline",

        'advisor.visual.support.inbox': 'Inbox Zero',
        'advisor.visual.support.desc': 'All 42 morning tickets have been resolved instantly. Your customers are happy.',
        'advisor.visual.support.score': 'Average CSAT Score: 5.0',

        'advisor.visual.recep.header': 'CALENDAR · TODAY',
        'advisor.visual.recep.event1': '09:00 AM · Client Onboarding',
        'advisor.visual.recep.event2': '11:30 AM · Strategy Call',
        'advisor.visual.recep.event3': '02:00 PM · New Lead Demo',
        'advisor.visual.recep.free': 'Free Slot',
        'advisor.visual.recep.quote': '"I filled your canceled slot with a new lead."',

        'advisor.visual.recruiter.match': '98% Match',
        'advisor.visual.recruiter.btn_schedule': 'Schedule',
        'advisor.visual.recruiter.btn_cv': 'View CV',
        'advisor.visual.recruiter.footer': 'Scheduling interviews with 15 candidates...',

        // Pricing
        'pricing.per_month': '/mo',
        'pricing.title': 'Costs less',
        'pricing.title_suffix': 'than your coffee.',
        'pricing.subtitle': '14 days free on all plans. No card required.',
        'pricing.starter': 'Starter',
        'pricing.starter.sub': 'For individuals',
        'pricing.starter.f1': '1 AI Employee', 'pricing.starter.f2': '3 Integrations', 'pricing.starter.f3': '500 conversations/month', 'pricing.starter.f4': 'WhatsApp + Telegram',

        'pricing.pro': 'Pro',
        'pricing.pro.sub': 'For growing businesses',
        'pricing.pro.f1': '5 AI Employees', 'pricing.pro.f2': 'All 100+ Integrations', 'pricing.pro.f3': 'Unlimited conversations', 'pricing.pro.f4': 'Advanced Analytics', 'pricing.pro.f5': 'Priority Support',

        'pricing.biz': 'Business',
        'pricing.biz.sub': 'For agencies',
        'pricing.biz.f1': 'Unlimited Employees', 'pricing.biz.f2': 'White-labeling (Your brand)', 'pricing.biz.f3': 'Custom Integrations', 'pricing.biz.f4': 'Dedicated Server', 'pricing.biz.f5': '99.9% SLA',

        'pricing.cta.free': 'Try for free',
        'pricing.cta.plan': 'Choose plan',

        // Testimonials
        'testim.title': 'They already',
        'testim.title_suffix': 'switched.',
        'testim.quote1': "We set up our receptionist in 9 minutes. The next morning she had already booked 23 appointments while we were asleep.",
        'testim.author1': "MARIA K.",
        'testim.role1': "Bloom Beauty Studio",
        'testim.quote2': "Our sales manager used to lose leads after hours. Now X100 catches every single one. Revenue up 40% in the first month.",
        'testim.author2': "ARTEM V.",
        'testim.role2': "Forma Furniture",
        'testim.quote3': "I was skeptical — I'm not technical at all. But my assistant was running in under 10 minutes. It's like hiring someone who already knows the job.",
        'testim.author3': "OLGA S.",
        'testim.role3': "LegalEase Consulting",

        // Target Audience
        'target.title': 'Built for',
        'target.title_suffix': 'any industry.',
        'target.subtitle': 'If you sell services, products, or expertise, X100 adapts to your model instantly.',
        'target.ind.real_estate': 'Real Estate',
        'target.ind.dentistry': 'Dentistry',
        'target.ind.law': 'Law',
        'target.ind.beauty': 'Beauty Salons',
        'target.ind.auto': 'Auto Dealers',
        'target.ind.fitness': 'Fitness',
        'target.ind.restaurants': 'Restaurants',
        'target.ind.hospitality': 'Hospitality',
        'target.ind.home_services': 'Home Services',
        'target.ind.ecommerce': 'E-commerce',
        'target.ind.saas': 'SaaS Companies',
        'target.ind.marketing': 'Marketing',
        'target.ind.coaching': 'Online Coaching',
        'target.ind.recruitment': 'Recruitment',
        'target.ind.fintech': 'Fintech',
        'target.ind.creators': 'Creators',
        'target.ind.logistics': 'Logistics',
        'target.ind.clinics': 'Clinics',


    },
    ru: {
        'nav.products': 'Продукты',
        'nav.solutions': 'Решения',
        'nav.how_it_works': 'Как это работает',
        'nav.integrations': 'Интеграции',
        'nav.pricing': 'Цены',
        'nav.resources': 'Ресурсы',
        'nav.company': 'Компания',
        'nav.about': 'О нас',
        'nav.blog': 'Блог',
        'nav.careers': 'Карьера',
        'nav.contact': 'Контакты',
        'nav.login': 'Войти',
        'nav.book_demo': 'Заказать демо',
        'hero.title': 'Симулируйте свой штат сотрудников',
        'hero.subtitle': 'Создавайте ИИ-сотрудников, которые обучаются вашему бизнесу, квалифицируют лиды и закрывают сделки, пока вы спите.',
        'hero.cta.start': 'Начать бесплатно',
        'hero.cta.book': 'Заказать демо',
        'hero.promo': 'ИИ-сотрудники · Готовы за минуты',
        'hero.headline_prefix': 'Ваш лучший сотрудник',
        'hero.subheading': 'Наймите автономного цифрового сотрудника в одном разговоре. Без кода. Без обучения.',
        'hero.cta.create': 'Создать первого сотрудника — бесплатно',
        'hero.trusted': 'Нам доверяют',
        'hero.businesses': '2,400+ компаний',
        'hero.search_placeholder': 'Мне нужен кто-то для бронирования клиентов...',
        'hero.phrases.0': 'никогда не болеет.',
        'hero.phrases.1': 'работает 24/7.',
        'hero.phrases.2': 'масштабируется мгновенно.',
        'products.sales_manager': 'Менеджер по продажам',
        'products.receptionist': 'Ресепшионист',
        'products.support_agent': 'Агент поддержки',
        'products.content_manager': 'Контент-менеджер',
        'section.learn_more': 'Узнать больше',

        // Pain Section RU
        'pain.title': 'Звучит',
        'pain.title_suffix': 'знакомо?',
        'pain.subtitle': "Масштабировать бизнес сложно. Ограничения людей не должны быть узким местом.",
        'pain.quote1': "Клиент написал в 11 вечера, чтобы записаться.",
        'pain.quote1_highlight': "К утру он уже ушел к конкуренту.",
        'pain.quote2': "Ваш менеджер разрывается между звонками, WhatsApp, Instagram и таблицами.",
        'pain.quote3': "Вы наняли сотрудника, обучали его 3 недели,",
        'pain.quote3_highlight': "а он уволился через месяц.",
        'pain.quote4': "Вы платите полную зарплату тому, кто отвечает на одни и те же 10 вопросов каждый день.",

        // How It Works RU
        'how.title': 'Внедрение за',
        'how.title_suffix': 'минуты.',
        'how.subtitle': 'Наймите ИИ-команду, которая изучит ваш бизнес мгновенно.',
        'how.step1.title': '1. Выберите роль',
        'how.step1.desc': 'Скажите, кто вам нужен. Продавец, Ресепшионист или Агент поддержки.',
        'how.step2.title': '2. Загрузите знания',
        'how.step2.desc': 'Загрузите сайт, PDF или Notion. Агент изучит ваш бизнес моментально.',
        'how.step3.title': '3. Делегируйте',
        'how.step3.desc': 'Ваш агент начинает работать 24/7 в WhatsApp, Web и Telegram.',

        // Capabilities RU
        'cap.title': 'Реальная работа.',
        'cap.title_suffix': 'Не просто чат.',
        'cap.card1.title': 'Мгновенные ответы',
        'cap.card1.desc': 'Отвечает на каждое сообщение быстрее 5 секунд. Клиенты не ждут.',
        'cap.card2.title': 'Записи и Продажи',
        'cap.card2.desc': 'Квалифицирует лиды, записывает на встречи и принимает оплату автоматически.',
        'cap.card3.title': 'Полная интеграция',
        'cap.card3.desc': 'Логирует каждый диалог в CRM и обновляет календарь мгновенно.',

        // Catalog / Products RU
        'catalog.title': 'Готовы',
        'catalog.title_suffix': 'масштабироваться?',
        'catalog.subtitle': 'Специализированные ИИ-агенты для конкретных бизнес-задач с точностью человека.',

        'catalog.sales.title': 'ИИ Менеджер по продажам',
        'catalog.sales.desc': 'Ваш лучший продавец, доступный 24/7. Мгновенно вовлекает лидов, квалифицирует их по скрипту, отрабатывает возражения и закрывает сделки прямо в чате.',
        'catalog.sales.f1': 'Мгновенная квалификация',
        'catalog.sales.f2': 'Синхронизация HubSpot/Salesforce',
        'catalog.sales.f3': 'Умная работа с возражениями',
        'catalog.sales.f4': 'Каналы: WhatsApp, Web, Telegram',

        'catalog.reception.title': 'ИИ Ресепшионист',
        'catalog.reception.desc': 'Администратор, который не спит. Забудьте о пропущенных звонках. Этот агент ведет запись, переносит встречи и шлет напоминания, заполняя ваш календарь.',
        'catalog.reception.f1': 'Запись 24/7',
        'catalog.reception.f2': 'Google/Outlook/Calendly',
        'catalog.reception.f3': 'Ноль неявок (Smart Reminders)',
        'catalog.reception.f4': 'Умный перенос встреч',

        'catalog.support.title': 'ИИ Поддержка',
        'catalog.support.desc': 'Превратите поддержку в радость. Решает 80% тикетов мгновенно. Изучает базу знаний, трекает заказы и делает возвраты, эскалируя только сложные случаи.',
        'catalog.support.f1': 'Мгновенные ответы на FAQ',
        'catalog.support.f2': 'Трекинг заказов',
        'catalog.support.f3': 'Бесшовный перевод на человека',
        'catalog.support.f4': 'Поддержка 95+ языков',

        'catalog.content.title': 'ИИ Контент-менеджер',
        'catalog.content.desc': 'Ваша SMM команда 24/7. Ведет бренд без выгорания. Пишет посты, планирует контент и отвечает на комментарии для роста вовлеченности.',
        'catalog.content.f1': 'Пишет и планирует посты',
        'catalog.content.f2': 'Авто-ответы на комменты',
        'catalog.content.f3': 'Анализ вирусных трендов',
        'catalog.content.f4': 'Адаптируется под Tone of Voice',

        // Integrations RU
        'integ.title': '100+ Бесшовных Интеграций',
        'integ.desc': 'Подключайте любимые инструменты в один клик.',
        'integ.nocode': 'Без программирования.',
        'integ.desc2': 'Наш ИИ-движок мгновенно осваивает ваш стек и начинает бесперебойно работать на всех платформах.',
        'integ.soc2': 'SOC2 Compliant',
        'integ.visual.init': 'ИНИЦИАЛИЗАЦИЯ_ПРОТОКОЛА...',
        'integ.visual.target': 'Цель: 100+ Интеграций',

        // Comparison RU
        'comp.title': 'Цифры',
        'comp.title_suffix': "не лгут.",
        'comp.metric': 'Метрика',
        'comp.human': 'Человек',
        'comp.ai': 'X100 AI',
        'comp.m1': 'Время ответа', 'comp.h1': '2–8 часов', 'comp.a1': '3 секунды',
        'comp.m2': 'Доступность', 'comp.h2': '5 дней, 9-18', 'comp.a2': '24/7/365',
        'comp.m3': 'Стоимость/мес', 'comp.h3': '60 000 ₽+', 'comp.a3': 'от 14 900 ₽',
        'comp.m4': 'Обучение', 'comp.h4': '3–4 недели', 'comp.a4': '7 минут',
        'comp.m5': 'Параллельные чаты', 'comp.h5': '1–2', 'comp.a5': 'Безлимитно',
        'comp.disclaimer': "*X100 не заменяет людей. Он берет на себя рутину, чтобы команда занималась главным.",

        // Pricing RU
        'pricing.per_month': '/мес',
        'pricing.title': 'Стоит меньше',
        'pricing.title_suffix': 'чем кофе.',
        'pricing.subtitle': '14 дней бесплатно на всех тарифах. Карта не нужна.',
        'pricing.starter': 'Старт',
        'pricing.starter.sub': 'Для частных лиц',
        'pricing.starter.f1': '1 ИИ Сотрудник', 'pricing.starter.f2': '3 Интеграции', 'pricing.starter.f3': '500 диалогов/мес', 'pricing.starter.f4': 'WhatsApp + Telegram',

        'pricing.pro': 'Про',
        'pricing.pro.sub': 'Для растущего бизнеса',
        'pricing.pro.f1': '5 ИИ Сотрудников', 'pricing.pro.f2': 'Все 100+ Интеграций', 'pricing.pro.f3': 'Безлимит диалогов', 'pricing.pro.f4': 'Продвинутая аналитика', 'pricing.pro.f5': 'Приоритетная поддержка',

        'pricing.biz': 'Бизнес',
        'pricing.biz.sub': 'Для агентств',
        'pricing.biz.f1': 'Безлимит сотрудников', 'pricing.biz.f2': 'White-labeling (Ваш бренд)', 'pricing.biz.f3': 'Кастомные интеграции', 'pricing.biz.f4': 'Выделенный сервер', 'pricing.biz.f5': 'SLA 99.9%',

        'pricing.cta.free': 'Попробовать бесплатно',
        'pricing.cta.plan': 'Выбрать план',

        // Testimonials RU
        'testim.title': 'Они уже',
        'testim.title_suffix': 'перешли.',
        'testim.quote1': "Мы настроили ресепшиониста за 9 минут. На следующее утро она записала 23 встречи, пока мы спали.",
        'testim.author1': "МАРИЯ К.",
        'testim.role1': "Студия красоты Bloom",
        'testim.quote2': "Наш менеджер терял лидов после работы. Теперь X100 ловит каждого. Выручка выросла на 40% за первый месяц.",
        'testim.author2': "АРТЕМ В.",
        'testim.role2': "Мебель Forma",
        'testim.quote3': "Я была скептична — я совсем не технарь. Но мой ассистент заработал через 10 минут. Как будто наняла профи.",
        'testim.author3': "ОЛЬГА С.",
        'testim.role3': "Консалтинг LegalEase",

        // Target Audience RU
        'target.title': 'Создано для',
        'target.title_suffix': 'любой индустрии.',
        'target.subtitle': 'Если вы продаете услуги, товары или экспертизу, X100 адаптируется к вашей модели мгновенно.',
        'target.ind.real_estate': 'Недвижимость',
        'target.ind.dentistry': 'Стоматология',
        'target.ind.law': 'Юриспруденция',
        'target.ind.beauty': 'Салоны красоты',
        'target.ind.auto': 'Автодилеры',
        'target.ind.fitness': 'Фитнес',
        'target.ind.restaurants': 'Рестораны',
        'target.ind.hospitality': 'Отели',
        'target.ind.home_services': 'Бытовые услуги',
        'target.ind.ecommerce': 'E-commerce',
        'target.ind.saas': 'SaaS компании',
        'target.ind.marketing': 'Маркетинг',
        'target.ind.coaching': 'Онлайн-коучинг',
        'target.ind.recruitment': 'Рекрутинг',
        'target.ind.fintech': 'Финтех',
        'target.ind.creators': 'Блогеры',
        'target.ind.logistics': 'Логистика',
        'target.ind.clinics': 'Клиники',

        // Footer RU
        'footer.roi': 'Мгновенный ROI',
        'footer.title': 'Масштабируйте команду',
        'footer.title_suffix': 'без',
        'footer.title_suffix2': 'издержек.',
        'footer.subtitle': 'Запустите ИИ Менеджера или Агента поддержки сегодня. Ноль времени на обучение. Бесконечная масштабируемость.',
        'footer.cta': 'Нанять ИИ',
        'footer.stat.uptime': 'Аптайм',
        'footer.stat.automated': 'Автоматизация',
        'footer.card.growth_engine': 'Двигатель роста',
        'footer.card.running': 'Работает на 100%',
        'footer.card.leads': 'Обработано лидов',
        'footer.card.revenue': 'Сгенерировано выручки',
        'footer.card.team_perf': 'Эффективность команды: Полный вперед',
        'footer.col.roles': 'Роли',
        'footer.col.company': 'Компания',
        'footer.col.legal': 'Правовая информация',
        'footer.disclaimer': 'Создано для бизнеса, который не хочет терять ни одного клиента.',
        'footer.legal.copyright': '©2026 X100 Inc. Все права защищены.',
        'footer.legal.text': 'X100 создает автономных цифровых агентов. Результаты могут варьироваться в зависимости от конфигурации и данных для обучения.',
        'footer.email_placeholder': 'Введите ваш email',
        'footer.join': 'Присоединиться',
        'products.personal_assistant': 'Личный Ассистент',
        // Login
        'login.title': 'Начните работу',
        'login.title_suffix': 'с нами',
        'login.subtitle': 'Выполните эти простые шаги, чтобы получить доступ к вашим AI-сотрудникам и начать автоматизацию.',
        'login.step1': 'Войдите в аккаунт',
        'login.step2': 'Подключите агентов',
        'login.step3': 'Начните автоматизацию',
        'login.form.title': 'Вход в аккаунт',
        'login.form.subtitle': 'Введите ваши данные для доступа к рабочей области.',
        'login.email': 'Email',
        'login.password': 'Пароль',
        'login.forgot': 'Забыли пароль?',
        'login.min_chars': 'Минимум 8 символов.',
        'login.submit': 'Войти',
        'login.footer': 'Нет аккаунта?',
        'login.footer_link': 'Зарегистрироваться',
        // Register
        'register.title': 'Создайте своих',
        'register.title_suffix': 'цифровых сотрудников',
        'register.subtitle': 'Начните создавать AI сотрудников за минуты',
        'register.form.title': 'Создать аккаунт',
        'register.form.subtitle': 'Присоединяйтесь к тысячам компаний, автоматизирующих работу с AI',
        'register.company': 'Название компании',
        'register.submit': 'Создать аккаунт',
        'register.footer': 'Уже есть аккаунт?',
        'register.footer_link': 'Войти',
        // Features
        'features.title': 'Финансовое благополучие,',
        'features.title_suffix': 'заново.',
        'features.subtitle': 'Все необходимое для управления капиталом: от учета капитала до налогов, в одном месте.',
        'features.net_worth.title': 'Общий капитал',
        'features.net_worth.desc': 'Подключите все счета для полной картины. Отслеживание активов, обязательств и капитала в реальном времени.',
        'features.tax.title': 'Налоги',
        'features.tax.desc': 'Автоматическая подача деклараций, разработанная для современных компенсационных пакетов.',
        'features.equity.title': 'Управление долями',
        'features.equity.desc': 'Отслеживайте графики вестинга, исполняйте опционы и моделируйте будущие сценарии.',
        'features.retirement.title': 'Пенсия',
        'features.retirement.desc': 'Персонализированные планы, чтобы помочь вам быстрее достичь финансовой свободы.',
        'features.advisory.title': 'Экспертный совет',
        'features.advisory.desc': 'Неограниченный доступ к профессионалам CFP® для сложных вопросов.',
        'features.more_about': 'Подробнее о',
        // Impact Features
        'impact.title': 'Создано для',
        'impact.title_suffix': 'Роста.',
        'impact.subtitle': "X100 — это не просто ПО. Это масштабируемая инфраструктура, заменяющая издержки прибылью.",
        'impact.card1.title': 'Максимизация выручки',
        'impact.card1.desc': 'Агенты X100 никогда не спят. Каждый лид обрабатывается мгновенно, квалифицируется и записывается в ваш календарь.',
        'impact.card1.stat_label': 'Захват лидов',
        'impact.card2.title': 'Мгновенный масштаб',
        'impact.card2.desc': 'Обслуживайте 1 или 10 000 диалогов одновременно без найма новых сотрудников.',
        'impact.card3.title': 'Безопасность',
        'impact.card3.desc': 'Шифрование данных, ролевой доступ и соответствие GDPR встроены в платформу.',
        'impact.card4.title': 'Без человеческих ошибок',
        'impact.card4.desc': 'Забудьте о больничных и ошибках. Агенты X100 следуют вашим инструкциям идеально, каждый раз.',
        // Product Demo
        'demo.title': 'Полный',
        'demo.title_suffix': 'контроль.',
        'demo.subtitle': 'От создания до анализа — управляйте всем цифровым штатом из единого центра.',
        'demo.tab1': 'Создание',
        'demo.tab2': 'Управление',
        'demo.tab3': 'Масштаб',
        'demo.tab1.title': 'Архитектор',
        'demo.tab1.desc': 'Опишите идеального сотрудника простыми словами. Архитектор создаст агента, настроит инструменты и синхронизирует базу знаний.',
        'demo.tab2.title': 'Активный штат',
        'demo.tab2.desc': 'Ваша команда цифровых агентов на одном экране. Следите за статусом, ставьте на паузу или добавляйте новых в один клик.',
        'demo.tab3.title': 'Интеллект',
        'demo.tab3.desc': 'Отслеживайте эффективность в реальном времени. Видьте точно, сколько выручки приносят агенты и сколько часов экономят.',
        // Product Demo Mocks
        'demo.mock.chat.ai_greeting': 'Я Архитектор X100. Какого сотрудника вам нужно нанять сегодня?',
        'demo.mock.chat.user_req': 'Мне нужен менеджер по продажам для обработки входящих лидов с сайта и записи демо в мой календарь.',
        'demo.mock.chat.ai_response': "Понял. Я настраиваю",
        'demo.mock.chat.role_name': 'Менеджера по продажам',
        'demo.mock.chat.with_capabilities': 'со следующими возможностями:',
        'demo.mock.chat.cap1': 'Квалификация лидов',
        'demo.mock.chat.cap2': 'Синхронизация календаря',
        'demo.mock.chat.cap3': 'Обновление CRM',
        'demo.mock.chat.upload_prompt': 'Хотите загрузить PDF с ценами для обучения?',

        'demo.mock.workforce.title': 'Мой штат',
        'demo.mock.workforce.subtitle': 'Операции 24/7',
        'demo.mock.workforce.system': 'Системы в норме',
        'demo.mock.workforce.agent1.role': 'Агент по продажам',
        'demo.mock.workforce.agent1.metric1': 'Время ответа',
        'demo.mock.workforce.agent1.metric2': 'Сделок закрыто',
        'demo.mock.workforce.agent1.footer': 'Сэкономлено 42ч на этой неделе',
        'demo.mock.workforce.agent2.role': 'Ресепшионист',
        'demo.mock.workforce.agent2.metric1': 'Звонков принято',
        'demo.mock.workforce.agent2.metric2': 'Записей',
        'demo.mock.workforce.agent2.footer': '0 пропущенных',
        'demo.mock.workforce.hire': 'Нанять нового агента',

        'demo.mock.analytics.title': 'Показатели',
        'demo.mock.analytics.period': 'Последние 7 дней',
        'demo.mock.analytics.roi': 'ROI Сгенерировано',
        'demo.mock.analytics.man_hours': 'Человеко-часы',
        'demo.mock.analytics.saved': 'сэкономлено',
        'demo.mock.analytics.cost_lead': 'Стоимость/Лид',
        'demo.mock.analytics.avg': 'сред.',

        // Testimonial Marquee
        'testim.trusted': 'Нам доверяют 2,400+ компаний',
        'testim.switch': 'перешли.',
        'testim.subtitle': 'Посмотрите, как компании заменяют ручной труд автономными AI-агентами.',
        'testim.q1': "Мы настроили ресепшиониста за 9 минут. На следующее утро она записала 23 встречи, пока мы спали.",
        'testim.q2': "Наш менеджер по продажам терял лиды после работы. Теперь X100 ловит каждого. Выручка выросла на 40% в первый месяц.",
        'testim.q3': "Я был скептичен — я совсем не технарь. Но мой ассистент заработал через 10 минут. Это как нанять того, кто уже знает работу.",
        'testim.q4': "Время ответа сократилось с 4 часов до 30 секунд. Удовлетворенность клиентов достигла исторического максимума за неделю.",
        'testim.q5': "Проверил 500 резюме за день. Мы наняли топ-инженера за 3 дня. AI-рекрутер находит таланты, которых люди упускают.",
        'testim.q6': "Агент квалифицирует лиды 24/7. Я просыпаюсь с календарем, полным готовых к покупке клиентов. Это изменило мой бизнес.",
        'testim.q7': "Мгновенно отвечает на вопросы о возвратах. Поддержка наконец-то занялась сложными задачами вместо рутины.",
        'testim.q8': "Мы выросли до 50 клиентов без найма новых менеджеров. X100 идеально справляется с ежедневной коммуникацией.",
        'testim.q9': "Отвечает на каждый DM в Instagram. Продажи курсов удвоились с момента установки контент-менеджера. Абсолютный прорыв.",

        // Testimonial Authors & Roles RU
        'testim.n1': "Мария К.", 'testim.r1': "Студия красоты Bloom",
        'testim.n2': "Артем В.", 'testim.r2': "Мебель Forma",
        'testim.n3': "Ольга С.", 'testim.r3': "Консалтинг LegalEase",
        'testim.n4': "Лиам Т.", 'testim.r4': "Поддержка TechFlow",
        'testim.n5': "Сара Дж.", 'testim.r5': "HR Директор",
        'testim.n6': "Дэвид Р.", 'testim.r6': "Недвижимость Prime",
        'testim.n7': "Джеймс Л.", 'testim.r7': "Основатель E-commerce",
        'testim.n8': "Елена М.", 'testim.r8': "CEO Digital Агентства",
        'testim.n9': "Маркус Б.", 'testim.r9': "Коуч по эффективности",

        // Visual Mocks in ProductSections
        'visual.sales.user': 'Сколько стоит Enterprise?',
        'visual.sales.agent': 'Это 39 900 ₽/мес. Включает безлимитных агентов и аккаунт-менеджера. Хотите заказать демо?',
        'visual.sales.tag': 'Лид Квалифицирован: Горячий 🔥',

        'visual.reception.calendar': 'Календарь',
        'visual.reception.syncing': 'Синхронизация...',
        'visual.reception.booking': 'Запись: Сара Дж.',
        'visual.reception.time': 'Завтра, 10:00',
        'visual.reception.confirmed': 'Подтверждено',
        'visual.reception.haircut': 'Стрижка и укладка',
        'visual.reception.reminder': 'Напоминание отправлено',

        'visual.support.user': 'Где мой заказ #1234?',
        'visual.support.agent': 'Заказ #1234 передан курьеру! Будет у вас сегодня до 14:00. Вот ссылка для отслеживания.',
        'visual.support.kb': 'База знаний',
        'visual.support.response': 'Ответ: 1.2с',

        'visual.content.drafting': 'Черновик: Instagram Post',
        'visual.content.post': '"Повысьте эффективность с нашими новыми AI инструментами! 🚀 #Tech #AI"',

        // Capabilities Visuals
        'visual.cap.user': 'Есть свободное время завтра?',
        'visual.cap.agent_check': 'Проверяю календарь...',
        'visual.cap.agent_confirm': 'Да, есть слот в 14:00. Записать?',

        'visual.booking.new': 'Новое событие',
        'visual.booking.demo': 'Демо звонок',
        'visual.booking.time_label': 'Время',
        'visual.booking.time_val': 'Завтра, 10:00',
        'visual.booking.guest_label': 'Гость',
        'visual.booking.confirmed': 'Подтверждено',

        'visual.integration.hubspot': 'Контакт создан',
        'visual.integration.just_now': 'Только что',
        'visual.integration.salesforce': 'Этап сделки обновлен',
        'visual.integration.ago_2m': '2м назад',
        'visual.integration.slack': 'Уведомление отправлено',
        'visual.integration.ago_5m': '5м назад',
        'visual.integration.gmail': 'Фоллоу-ап запланирован',
        'visual.integration.ago_12m': '12м назад',
        'footer.nav.privacy': 'Политика конфиденциальности',
        'footer.nav.terms': 'Условия использования',
        'footer.nav.gdpr': 'GDPR',

        // Cookie Consent RU
        'cookie.title': '🍪 Настройки Cookie',
        'cookie.text': 'Мы используем куки для работы наших AI функций и анализа трафика. Личные данные не передаются третьим лицам.',
        'cookie.accept': 'Принять все',
        'cookie.decline': 'Только необходимые',

        // Insight Recap RU
        'recap.cta.title': 'X100 в Действии',
        'recap.cta.desc': 'Посмотрите, как создать полноценную службу поддержки менее чем за 10 минут.',
        'recap.cta.btn': 'Смотреть Демо',

        'recap.left.title_em': 'Мониторинг',
        'recap.left.title': 'эффективности',
        'recap.left.subtitle': 'Дашборд продуктивности вашего цифрового штата и вовлеченности клиентов в реальном времени.',
        'recap.left.card_title': 'Бот поддержки закрыл 1,500 тикетов',
        'recap.left.card_desc': 'Ваш агент первой линии успешно решил 98% входящих запросов за последние 24 часа. CSAT вырос до 4.9/5.',

        'recap.right.title_em': 'Ежедневные',
        'recap.right.title': 'бизнес-сводки',
        'recap.right.subtitle': 'Сводка эффективности бизнеса каждый день — будьте в курсе лидов, конверсий и операций.',
        'recap.right.card_title': '342 Новых Лида',
        'recap.right.card_desc': 'SEO-менеджер вывел в топ 3 новых статьи, что привело к скачку трафика на 20%.',
        'recap.right.recents': 'Последние Конверсии',
        'recap.right.report': 'Подробный Отчет',

        'recap.tx.ent': 'Enterprise План', 'recap.tx.ent_sub': 'Агент Продаж · 10 мин назад',
        'recap.tx.start': 'Starter План', 'recap.tx.start_sub': 'Web Бот · 1 час назад',
        'recap.tx.consult': 'Консультация', 'recap.tx.consult_sub': 'Бот Бронирования · 2 часа назад',

        // Gemini Advisor RU
        'advisor.title': 'Смоделируйте', 'advisor.title_suffix': 'штат сотрудников.',
        'advisor.subtitle': 'Посмотрите, как ИИ-сотрудник впишется в ваш бизнес. Без кода, без сложностей.',
        'advisor.status': 'Активен сейчас',
        'advisor.active': 'Активен сейчас',
        'advisor.cost': 'Стоимость',
        'advisor.human': 'Человеческий эквивалент',
        'advisor.price.89': '24 900 ₽/мес',
        'advisor.price.5000': '500 000 ₽/мес',
        'advisor.price.3500': '350 000 ₽/мес',
        'advisor.price.3000': '300 000 ₽/мес',
        'advisor.price.4500': '450 000 ₽/мес',

        // Agents RU
        'advisor.agent.sales.name': 'Менеджер Продаж', 'advisor.agent.sales.role': 'Рост Выручки',
        'advisor.agent.sales.desc': "Я обрабатываю лиды 24/7. Пока вы спите, я общаюсь с клиентами в WhatsApp, работаю с возражениями и закрываю сделки.",
        'advisor.agent.sales.benefit': "Разбудит вас уведомлением 'Оплата получена'.",

        'advisor.agent.support.name': 'Агент Поддержки', 'advisor.agent.support.role': 'Успех Клиентов',
        'advisor.agent.support.desc': "Я помню всю вашу базу знаний. Оформляю возвраты, отслеживаю заказы и отвечаю на технические вопросы мгновенно.",
        'advisor.agent.support.benefit': "Достигает 'Empty Inbox' каждый день.",

        'advisor.agent.receptionist.name': 'Ресепшионист', 'advisor.agent.receptionist.role': 'Администратор',
        'advisor.agent.receptionist.desc': "Я управляю вашим календарем как профи. Бронирую слоты, отправляю напоминания и переношу встречи без вашего участия.",
        'advisor.agent.receptionist.benefit': "Заполняет ваш календарь целевыми встречами.",

        'advisor.agent.recruiter.name': 'HR Рекрутер', 'advisor.agent.recruiter.role': 'Подбор Талантов',
        'advisor.agent.recruiter.desc': "Я читаю тысячи резюме за минуты. Нахожу топ-1% талантов и назначаю собеседования для вас.",
        'advisor.agent.recruiter.benefit': "Приносит идеального кандидата на блюдечке.",

        // Visuals RU
        'advisor.visual.sales.p1.title': 'Платеж Stripe: 120 000 ₽', 'advisor.visual.sales.p1.sub': 'Закрыто из WhatsApp',
        'advisor.visual.sales.p2.title': 'Лид Квалифицирован', 'advisor.visual.sales.p2.sub': 'Бюджет: Enterprise • Готов',
        'advisor.visual.sales.p3.title': 'Демо Забронировано', 'advisor.visual.sales.p3.sub': 'Авто-запись в Календарь',
        'advisor.visual.sales.today': "Пайплайн сегодня",

        'advisor.visual.support.inbox': 'Пустой Инбокс',
        'advisor.visual.support.desc': 'Все 42 утренних тикета решены мгновенно. Ваши клиенты счастливы.',
        'advisor.visual.support.score': 'Средний CSAT: 5.0',

        'advisor.visual.recep.header': 'КАЛЕНДАРЬ · СЕГОДНЯ',
        'advisor.visual.recep.event1': '09:00 · Онбординг клиента',
        'advisor.visual.recep.event2': '11:30 · Стратегия',
        'advisor.visual.recep.event3': '14:00 · Демо с лидом',
        'advisor.visual.recep.free': 'Свободный слот',
        'advisor.visual.recep.quote': '"Я заполнил отмененный слот новым лидом."',

        'advisor.visual.recruiter.match': '98% Совпадение',
        'advisor.visual.recruiter.btn_schedule': 'Назначить',
        'advisor.visual.recruiter.btn_cv': 'Смотреть CV',
        'advisor.visual.recruiter.footer': 'Отфильтровано 450 резюме. Найдено 3 лучших.',

        // About Page
        'about.mission.title': 'Наша',
        'about.mission.title_suffix': 'миссия.',
        'about.mission.subtitle': 'Мы создаем автономную рабочую силу будущего. Наша цель — освободить людей от рутинных задач, позволив им сосредоточиться на креативности, стратегии и инновациях.',
        'about.problem.title': 'Проблема',
        'about.problem.title_suffix': '',
        'about.problem.p1': 'Десятилетиями бизнес масштабировался за счет найма новых сотрудников. Эта линейная модель сломана. Она медленная, дорогая и стрессовая. Люди выгорают. Они ошибаются. Им нужен сон.',
        'about.problem.p2': 'Мы считаем, что 80% современной интеллектуальной работы повторяется и может быть автоматизирована. Тем не менее, большинство инструментов автоматизации слишком жесткие или слишком сложные в настройке.',
        'about.problem.visual': 'Визуал: График Человек vs Машина',
        'about.solution.title': 'Решение:',
        'about.solution.title_suffix': 'X100',
        'about.solution.p1': 'X100 — это не просто чат-бот. Это комплексная архитектура специализированных агентов. Мы создаем цифровых сотрудников, которые могут учиться, адаптироваться и выполнять сложные рабочие процессы без надзора.',
        'about.solution.p2': 'Наши агенты не просто «говорят» — они «делают». Они получают доступ к вашей CRM, управляют вашим календарем и обрабатывают платежи. Это настоящие автономные сущности.',
        'about.solution.visual': 'Визуал: Нейронная сеть агента',
        'about.leadership.title': 'Руководство',
        'about.team.david.name': 'Дэвид Чен',
        'about.team.david.role': 'CEO и основатель',
        'about.team.sarah.name': 'Сара Миллер',
        'about.team.sarah.role': 'CTO',
        'about.team.james.name': 'Джеймс Уилсон',
        'about.team.james.role': 'Глава AI-отдела',

        // Blog Page
        'blog.title': 'Сигнал',
        'blog.title_suffix': '',
        'blog.subtitle': 'Инсайты об ИИ, автоматизации и будущем работы.',
        'blog.read_article': 'Читать статью',
        'blog.back_to_blog': 'Назад к блогу',
        'blog.read_next': 'Читать далее',

        'blog.post1.title': 'Смерть колл-центра: Почему ИИ-агенты неизбежны',
        'blog.post1.date': '12 фев, 2026',
        'blog.post1.author': 'Алекс В.',
        'blog.post1.summary': 'Традиционные колл-центры дороги, неэффективны и подвержены человеческим ошибкам. ИИ-агенты обрабатывают поддержку 24/7 с нулевым временем ожидания.',

        'blog.post2.title': 'Как обучить вашего ИИ-менеджера по продажам за 7 минут',
        'blog.post2.date': '8 фев, 2026',
        'blog.post2.author': 'Сара Дж.',
        'blog.post2.summary': 'Вам не нужен разработчик. Загрузите PDF-файлы, синхронизируйте сайт и наблюдайте, как ИИ-агент автоматически квалифицирует лиды.',

        'blog.post3.title': 'Экономика ИИ: Расчет ROI для малого бизнеса',
        'blog.post3.date': '28 янв, 2026',
        'blog.post3.author': 'Дэвид Р.',
        'blog.post3.summary': 'Сравните стоимость штатного сотрудника с ИИ-агентом. Математика проста: в 10 раз больше производительности за 1/100 цены.',

        'blog.post4.title': 'Голосовой ИИ против текстового ИИ: Что нужно вашему бизнесу?',
        'blog.post4.date': '15 янв, 2026',
        'blog.post4.author': 'Майкл Т.',
        'blog.post4.summary': 'Голосовые агенты обрабатывают телефонные звонки с человеческими нюансами. Текстовые агенты доминируют в чатах. Вот как выбрать правильный микс.',

        'blog.post5.title': 'Будущее работы: Управление гибридной командой люди-ИИ',
        'blog.post5.date': '3 янв, 2026',
        'blog.post5.author': 'Эмма У.',
        'blog.post5.summary': 'ИИ не заменяет людей; он дополняет их. Узнайте, как структурировать команду, где ИИ выполняет рутину, а люди — стратегию.',

        // Contact Page
        'contact.title': 'Свяжитесь',
        'contact.title_suffix': 'с нами.',
        'contact.subtitle': 'Если у вас есть вопрос о функциях, ценах или корпоративных решениях, наша команда готова ответить.',
        'contact.headquarters': 'Штаб-квартира',
        'contact.headquarters.address': 'Market Street 100, Suite 500',
        'contact.headquarters.city': 'Сан-Франциско, CA 94103',
        'contact.email': 'Email',
        'contact.email.hello': 'hello@x100.ai',
        'contact.email.support': 'support@x100.ai',
        'contact.follow': 'Мы в соцсетях',
        'contact.social.twitter': 'Twitter/X',
        'contact.social.linkedin': 'LinkedIn',
        'contact.social.instagram': 'Instagram',
        'contact.form.name': 'Имя',
        'contact.form.email': 'Email',
        'contact.form.message': 'Сообщение',
        'contact.form.name.placeholder': 'Иван Иванов',
        'contact.form.email.placeholder': 'ivan@company.com',
        'contact.form.message.placeholder': 'Как мы можем вам помочь?',
        'contact.form.submit': 'Отправить',
        'contact.form.sending': 'Отправка...',
        'contact.success.title': 'Сообщение отправлено',
        'contact.success.subtitle': 'Мы ответим вам в течение 24 часов.',
        'contact.success.send_another': 'Отправить еще одно сообщение',

        // Careers Page
        'careers.title': 'Присоединяйтесь к',
        'careers.title_suffix': 'революции.',
        'careers.subtitle': 'Мы команда строителей, мечтателей и оптимистов. Мы нанимаем самых умных людей в мире для решения самых сложных проблем в области ИИ.',
        'careers.autonomy.title': 'Автономия',
        'careers.autonomy.desc': 'Мы не микроменеджим. Мы нанимаем взрослых и даем им свободу действий. Вы владеете своими проектами от начала до конца.',
        'careers.impact.title': 'Влияние',
        'careers.impact.desc': 'Ваша работа напрямую повлияет на тысячи бизнесов. Мы меняем саму ткань функционирования экономики.',
        'careers.positions.title': 'Открытые',
        'careers.positions.title_suffix': 'вакансии',
        'careers.job1.title': 'Senior AI-инженер',
        'careers.job1.department': 'Разработка',
        'careers.job1.location': 'Удаленно (весь мир)',
        'careers.job1.type': 'Полная занятость',
        'careers.job2.title': 'Продуктовый дизайнер',
        'careers.job2.department': 'Дизайн',
        'careers.job2.location': 'Удаленно (США/ЕС)',
        'careers.job2.type': 'Полная занятость',
        'careers.job3.title': 'Руководитель корпоративных продаж',
        'careers.job3.department': 'Продажи',
        'careers.job3.location': 'Нью-Йорк, NY',
        'careers.job3.type': 'Полная занятость',
        'careers.job4.title': 'Менеджер по маркетингу роста',
        'careers.job4.department': 'Маркетинг',
        'careers.job4.location': 'Удаленно',
        'careers.job4.type': 'Полная занятость',
        'careers.no_fit': 'Не нашли подходящую роль?',
        'careers.general_application': 'Отправить общее резюме',
    },
};

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
    const [language, setLanguage] = useState<Language>('en');

    const t = (key: string) => {
        // Return translation or key if missing
        return translations[language][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useTranslation = () => {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error('useTranslation must be used within a LanguageProvider');
    }
    return context;
};
